twig:
    default_path: '%kernel.project_dir%/src/View'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: false
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
